/* PRODUCT CATALOGUE
   To add a product: copy one object, give it a unique id, edit the fields,
   and paste your real Selar/Gumroad checkout URL into checkoutUrl.
*/
window.PRODUCTS = [
  {id:"500-business-prompts",name:"500 ChatGPT Prompts for Business Owners",category:"Business Resources",price:"Add price",short:"A structured prompt library designed to help business owners plan, market, sell, operate and grow more efficiently.",description:"A comprehensive collection of practical prompts covering core business activities. Designed as a ready-to-use productivity resource for entrepreneurs and small-business owners.",features:["500 organized business prompts","Practical business use cases","Designed for quick reference","Digital delivery"],checkoutUrl:"",status:"coming-soon"},
  {id:"pdf-automation-starter",name:"PDF Automation Business Starter",category:"Automation",price:"Add price",short:"Resources for designing practical PDF and business-document automation workflows.",description:"A practical digital resource for people exploring document automation as a service or product opportunity.",features:["Workflow ideas","Implementation guidance","Business-use examples","Digital delivery"],checkoutUrl:"",status:"coming-soon"},
  {id:"invoice-extraction",name:"Invoice Data Extraction Toolkit",category:"Business Software",price:"Add price",short:"A practical toolkit concept for extracting, reviewing and exporting structured invoice information.",description:"Designed for small businesses and finance workflows that need a more structured path from invoices to usable data.",features:["Invoice workflow","Human review step","Export-ready structure","International-use orientation"],checkoutUrl:"",status:"coming-soon"},
  {id:"payroll-payslip",name:"Payroll & Payslip Automation System",category:"Business Software",price:"Contact for deployment",short:"A configurable payroll and payslip workflow for organizations that want to reduce repetitive monthly processing.",description:"A configurable solution concept covering salary components, deductions, branded payslips and distribution workflows.",features:["Configurable salary components","Branded payslip output","Organizational deployment","Workflow automation"],checkoutUrl:"mailto:badmurs0@gmail.com?subject=Payroll%20and%20Payslip%20Automation%20Enquiry",status:"service"}
];
