/* Display catalogue only. Payable amounts are authoritative in api/_products.js. */
window.PRODUCTS = [
  {id:"500-business-prompts",name:"500 ChatGPT Prompts for Business Owners",category:"Business Resources",price:"₦7,500 / $9",short:"500 practical prompts for planning, marketing, sales, customer service and everyday business operations.",description:"A practical workbook containing 500 organized business prompts, input guidance, follow-ups, demonstrations and business workflows.",features:["500 core prompts in 20 chapters","Input guidance and follow-ups","Business demonstrations and workflows","Secure digital buyer package"],paymentEnabled:true,status:"live"},
{id:"ai-side-hustles",name:"AI Side Hustles Blueprint",category:"Business Resources",price:"₦12,000 / $15",short:"A practical guide to selecting, validating and delivering AI-assisted service opportunities.",description:"Covers practical AI-assisted offers, workflows, pricing and capacity planning, customer acquisition and quality-controlled delivery.",features:["20 opportunity profiles","Practical walkthroughs","Worksheets and implementation resources","Buyer package delivery"],paymentEnabled:true,status:"live"},
  {id:"remote-job-2026-2027",name:"How to Get a Remote Job: 2026/2027 Edition",category:"Career Guides",price:"₦10,000 / $12",short:"A structured guide to remote-job readiness, applications, interviews and safer vacancy screening.",description:"A practical guide to identifying suitable remote roles, preparing credible evidence and applications, screening vacancies and preparing for interviews.",features:["Remote role screening","CV and application guidance","Interview preparation","Companion resources"],paymentEnabled:true,status:"live"},
  {id:"scholarships-abroad",name:"How to Win Scholarships Abroad",category:"Education Guides",price:"₦12,000 / $15",short:"A practical guide to finding suitable funding opportunities and preparing credible applications.",description:"Covers eligibility, funding coverage, application planning, research proposals, references, interviews and scam detection.",features:["Eligibility and funding checks","Application planning","Research and reference guidance","Worksheets and resources"],paymentEnabled:false,status:"setup"},
  {id:"first-upwork-client",name:"How to Get Your First Upwork Client",category:"Career Guides",price:"₦10,000 / $12",short:"A practical guide to portfolios, proposals, job screening and safe project delivery on Upwork.",description:"Designed for skilled beginners seeking a disciplined route to their first Upwork contract without unrealistic income promises.",features:["Portfolio preparation","Job screening and proposal guidance","Pricing and delivery resources","Buyer companion files"],paymentEnabled:false,status:"setup"},
  {id:"five-guide-bundle",name:"BGM Five-Guide Bundle",category:"Bundles",price:"₦35,000 / $39",short:"All five BGM guides in one digital collection at a bundled price.",description:"Includes the five BGM guides and their supplied companion buyer materials. Digital delivery only; no guaranteed jobs, scholarships, clients or earnings.",features:["All five guides","Companion buyer materials","One purchase","Best-value bundle"],paymentEnabled:false,status:"setup",badge:"BEST VALUE"},
  {id:"payroll-payslip",name:"Payroll & Payslip Automation System",category:"Business Software",price:"Contact for deployment",short:"A configurable payroll and payslip workflow for organizations that want to reduce repetitive monthly processing.",description:"A configurable solution concept covering salary components, deductions, branded payslips and distribution workflows.",features:["Configurable salary components","Branded payslip output","Organizational deployment","Workflow automation"],checkoutUrl:"mailto:badmurs0@gmail.com?subject=Payroll%20and%20Payslip%20Automation%20Enquiry",status:"service"}
];


